### ISSUE TITLE
markdownView添加到scrollView上高度不对

### ISSUE THREAD

**Issue by 0xIce** [EyreFree/EFMarkdown#2]
如果把EFMarkdownView添加到一个scrollView上的话，在onRender回调里面返回的height不对,比正常的大太多了

**Comment by 0xIce** [comment]
应该是index.html里面的问题

**Comment by EyreFree** [comment]
唔，最近比较忙...大佬修好的话可以提个 PR，或者过段时间我看下...👍🏻

**Comment by 0xIce** [comment]
目前发现计算出来的高度是正常高度的四倍，并不知道原因😳

**Comment by EyreFree** [comment]
@hotchner 该问题已在 [0.0.5](https://github.com/EyreFree/EFMarkdown/releases/tag/0.0.5) 版本中修复。

**Comment by 0xIce** [comment]
辛苦大牛
