### ISSUE TITLE
无法编译！

### ISSUE THREAD

**Issue by nenhall** [EyreFree/EFMarkdown#5]
无法编译！报找不到 EFMarkdown
xcode9.3

**Comment by EyreFree** [comment]
麻烦提供一下详细的报错日志和复现步骤，感谢！

**Comment by nenhall** [comment]
pod install 然后打开demo工程，编译就一直报找不到 EFCMark库，实际pod里面已经有了！后面换了二台脑重新pod install，有一台直接编译过了，目前我也不知道什么原因

**Comment by nenhall** [comment]
重新验证了，是工程配置的问题；基于你的代码我重封装了套OC版本的

**Comment by xiaohange** [comment]
@nenhall 可否共享一下封装代码?
